import { Icon } from "@iconify/react";

const outline = {
  account: <Icon icon="ic:outline-account-circle" />,
  home: <Icon icon="bx:home" />,
  segmentation: <Icon icon="carbon:analytics" />,
  logout: <Icon icon="ic:outline-logout" />,
  login: <Icon icon="ic:outline-login" />,
  google: <Icon icon="ant-design:google-outlined" />,
  guest: <Icon icon="fluent:guest-16-regular" />,
  plus: <Icon icon="akar-icons:circle-plus" />,
  delete: <Icon icon="typcn:delete-outline" />,
  trash: <Icon icon="fa:trash-o" />,
  edit: <Icon icon="akar-icons:edit" />,
  hamburger: <Icon icon="radix-icons:hamburger-menu" />,
  chevron_down: <Icon icon="akar-icons:circle-chevron-down" />,
  chevron_up: <Icon icon="akar-icons:circle-chevron-up" />,
  chevron_left: <Icon icon="akar-icons:circle-chevron-left" />,
  chevron_right: <Icon icon="akar-icons:circle-chevron-right" />,
  history: <Icon icon="icon-park-outline:history" />,
  dots: <Icon icon="bi:three-dots" />,
  bar_chart: <Icon icon="bi:bar-chart" />,
  pie_chart: <Icon icon="bi:pie-chart" />,
  line_chart: <Icon icon="healthicons:chart-line" />,
  scatter_chart: <Icon icon="carbon:chart-scatter" />,
  geo_chart: <Icon icon="gis:world-map-alt" />,
  pin: <Icon icon="bi:pin-angle" />,
  download: <Icon icon="akar-icons:download" />,
  money: <Icon icon="healthicons:money-bag-outline" />,
  transactions: <Icon icon="icon-park-outline:bill" />,
  age: <Icon icon="cil:baby-carriage" />,
  gender: <Icon icon="icons8:gender" />,
  country: <Icon icon="bi:flag" />,
  city: <Icon icon="healthicons:city-outline" />,
  job_title: <Icon icon="healthicons:city-worker-outline" />,
  job_industry: <Icon icon="cil:industry" />,
  broom: <Icon icon="la:broom" />,
  back: <Icon icon="akar-icons:arrow-back" />,
};

const solid = {
  account: <Icon icon="ic:baseline-account-circle" />,
  home: <Icon icon="bxs:home" />,
  potentiality: <Icon icon="ic:baseline-batch-prediction" />,
  login: <Icon icon="ic:outline-login" />,
  logout: <Icon icon="ic:baseline-logout" />,
  google: <Icon icon="ant-design:google-circle-filled" />,
  guest: <Icon icon="fluent:guest-16-filled" />,
  plus: <Icon icon="akar-icons:circle-plus-fill" />,
  delete: <Icon icon="typcn:delete" />,
  trash: <Icon icon="fa:trash" />,
  options_vertical: <Icon icon="mi:options-vertical" />,
  options_horizontal: <Icon icon="mi:options-horizontal" />,
  chevron_down: <Icon icon="akar-icons:circle-chevron-down-fill" />,
  chevron_up: <Icon icon="akar-icons:circle-chevron-up-fill" />,
  chevron_left: <Icon icon="akar-icons:circle-chevron-left-fill" />,
  chevron_right: <Icon icon="akar-icons:circle-chevron-right-fill" />,
  bar_chart: <Icon icon="bi:bar-chart-fill" />,
  pie_chart: <Icon icon="bi:pie-chart-fill" />,
  line_chart: <Icon icon="healthicons:chart-line-negative" />,
  geo_chart: <Icon icon="gis:world-map-alt-o" />,
  pin: <Icon icon="bi:pin-angle-fill" />,
  money: <Icon icon="healthicons:money-bag" />,
  transaction: <Icon icon="icon-park-solid:bill" />,
  age: <Icon icon="bxs:baby-carriage" />,
  country: <Icon icon="bi:flag-fill" />,
  city: <Icon icon="healthicons:city" />,
  job_title: <Icon icon="healthicons:city-worker" />,
};

const colored = {
  google: <Icon icon="flat-color-icons:google" />,
};

const icons = { outline, solid, colored };

export default icons;
